# Generated by Django 3.1.7 on 2021-03-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210305_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shippingCity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shippingCountry',
        ),
    ]
