# Generated by Django 3.1.7 on 2021-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('stok', models.IntegerField()),
                ('img_url', models.ImageField(upload_to='productos/images')),
                ('tag_use', models.CharField(choices=[('moda', 'Productos de moda'), ('aseo', 'Productos de aseo personal'), ('manufactura', 'Productos de manufactura')], max_length=50)),
            ],
        ),
    ]
