# Generated by Django 3.1.7 on 2021-03-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210301_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stok',
            field=models.CharField(max_length=10),
        ),
    ]
