# Generated by Django 3.1.7 on 2021-03-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20210301_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tag_use',
            field=models.CharField(choices=[('Moda', 'Productos de Moda'), ('Limpieza', 'Productos de Limpieza'), ('Manufactura', 'Productos de Manufactura')], max_length=50),
        ),
    ]
