# Generated by Django 3.1.7 on 2021-03-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coment', to='productos.producto'),
        ),
    ]
