# Generated by Django 3.1.7 on 2021-03-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20210304_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img_url',
            field=models.ImageField(upload_to='./productos/images'),
        ),
    ]
