# Generated by Django 3.1.7 on 2021-03-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20210304_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_name', models.CharField(max_length=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
