# Generated by Django 3.1.7 on 2021-03-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_cupones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Name',
            new_name='name',
        ),
    ]
