# Generated by Django 3.1.7 on 2021-03-05 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210304_1917'),
        ('productos', '0012_auto_20210304_1917'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('merchanID', models.IntegerField(default=12345)),
                ('referenceCode', models.CharField(default='esteesuncodigode', max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_product', to='productos.producto')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_profile', to='users.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
