# Generated by Django 3.1.7 on 2021-03-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210304_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='referenceCode',
            field=models.CharField(default='aasndsddskn', max_length=20),
        ),
    ]
