# Generated by Django 3.1.7 on 2021-03-05 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20210305_0124'),
        ('compras', '0003_auto_20210304_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_compra', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='referenceCode',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
