# Generated by Django 3.1.7 on 2021-03-05 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210305_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='referenceCode',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
